version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - 8000:8000
    command: uvicorn src.main:app --reload

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
