name: Stage
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'
            cache: 'pip'
      - run: echo 'The triggering workflow succeed'
  on-failure:
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
